src/objects/Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Period_Term__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Period Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Configuration</label>
</CustomObject>

src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Added_Date__c</fullName>
        <label>Added Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>Product Tables</relationshipLabel>
        <relationshipName>Product_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Warehouse__c.object
<CustomObject>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignProductToWarehouseTriggerHandler.cls
/**
 * Created by alaputsky on 9/4/2019.
 */

public class AssignProductToWarehouseTriggerHandler {

    public static List<Product_Table__c> productAssignment(List<Product_Table__c> createdAndUpdatedProducts) {

        List<Warehouse__c> warehouses = new List<Warehouse__c>();
        List<Warehouse__c> newWarehouses = new List<Warehouse__c>();

        warehouses = [
                SELECT Id, Name, Period_Start__c, Period_End__c
                FROM Warehouse__c
        ];

        for (Product_Table__c product : createdAndUpdatedProducts) {
            if(product.Added_Date__c == null) {
                product.Added_Date__c = Date.today();
            }
        }

        for (Product_Table__c product : createdAndUpdatedProducts) {
            if(product.Warehouse__c == null) {
                if (warehouses.isEmpty()) {
                    newWarehouses.add(createWarehouse(product));
                }
                for (Warehouse__c warehouse : warehouses) {
                    if (warehouse.Period_Start__c <= product.Added_Date__c && warehouse.Period_End__c >= product.Added_Date__c) {
                        product.Warehouse__c = warehouse.Id;
                        break;
                    } else {
                        newWarehouses.add(createWarehouse(product));
                    }
                }
            }
        }

        if(newWarehouses != null) {
            insert newWarehouses;
            for (Product_Table__c product : createdAndUpdatedProducts) {
                for (Warehouse__c warehouse : newWarehouses) {
                    if (warehouse.Period_Start__c <= product.Added_Date__c && warehouse.Period_End__c >= product.Added_Date__c) {
                        product.Warehouse__c = warehouse.Id;
                    }
                }
            }
        }

        return createdAndUpdatedProducts;
    }

    private static Warehouse__c createWarehouse(Product_Table__c product) {
        Integer periodTerm = 0;
        Configuration__c config = [
                SELECT Id, Period_Term__c
                FROM Configuration__c
        ];

        if(config != null) {
            periodTerm = Integer.valueOf(config.Period_Term__c);
        }

        Warehouse__c newWarehouse = new Warehouse__c(
                Name = 'Warehouse' + product.Added_Date__c + ' ' + product.Added_Date__c.addDays(periodTerm),
                Period_Start__c = product.Added_Date__c,
                Period_End__c = product.Added_Date__c.addDays(periodTerm)
        );

        return newWarehouse;
    }

}