src/objects/Order_Table__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product_Table__c</referenceTo>
        <relationshipLabel>Order Tables</relationshipLabel>
        <relationshipName>Order_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Table</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderTableController.cls
/**
 * Created by alaputsky on 9/9/2019.
 */

public with sharing class OrderTableController {

    public List <Product_Table__c> products { get; set; }
    public List <Contact> contacts { get; set; }
    public String productId { get; set; }
    public String FirstName { get; set; }
    public String LastName { get; set; }
    public String Email { get; set; }
    public Integer quantity { get; set; }

    public OrderTableController() {
        productId = ApexPages.currentPage().getParameters().get('Id');
        products = [
                SELECT Id, Name, Unit_Price__c, Units_Available__c
                FROM Product_Table__c
                WHERE Id = :productId
        ];
    }

    public PageReference redirectBack() {
        PageReference pageRef = Page.ProductTableVF;
        pageRef.setRedirect(true);
        return pageRef;
    }

    public String checkOut() {
        contacts = [
                SELECT Email, FirstName, LastName
                FROM Contact
                WHERE Email = :Email
        ];

        if(contacts.isEmpty()) {
            Contact newContact = new Contact(
                    FirstName = FirstName,
                    LastName = LastName,
                    Email = Email);
            try {
                insert newContact;
                contacts.add(newContact);
            } catch (DmlException ex) {
                return null;
            }
        } else {
            for (Integer i = 0; i < contacts.size(); i++) {
                contacts[i].FirstName = FirstName;
                contacts[i].LastName = LastName;
            }
            try {
                update contacts;
            } catch (DmlException ex) {
                return null;
            }
        }

        insertOrder();

        return null;
    }

    public void insertOrder() {
        Decimal Order_Amount = (quantity * products[0].Unit_Price__c);
        Order_Table__c  order = new Order_Table__c (
                Contact__c = contacts[0].Id,
                Product__c = productId,
                Units__c = quantity,
                Order_Amount__c = Order_Amount);

        products[0].Units_Available__c = products[0].Units_Available__c - Decimal.valueOf(quantity);

        if(quantity > 0) {
            if (products[0].Units_Available__c >= 0) {
                update products;
                insert order;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Заказ принят!'));
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Недостаточно товара!'));
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'ВВедите положительное количество товара!'));
        }
    }
}