src/objects/Product_Table__c.object
<CustomObject>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>Product Tables</relationshipLabel>
        <relationshipName>Product_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Warehouse__c.object
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductTableControllerTest.cls
/**
 * Created by alaputsky on 9/10/2019.
 */
@isTest
public with sharing class ProductTableControllerTest {
    @testSetup static void setup() {
        Warehouse__c warehouse = new Warehouse__c(Name = 'test');
        insert warehouse;

        List<Product_Table__c> products = new List<Product_Table__c>();
        Product_Table__c product1 = new Product_Table__c(
                Name = 'Iphone',
                Product_Description__c = 'Lorem Ipsum Dolor Sit Amet.',
                Unit_Price__c = 1000,
                Units_Available__c = 10,
                Warehouse__c = warehouse.Id
        );
        products.add(product1);

        Product_Table__c product2 = new Product_Table__c(
                Name = 'Xiaomi',
                Product_Description__c = 'Lorem Ipsum Dolor Sit Amet.',
                Unit_Price__c = 500,
                Units_Available__c = 5,
                Warehouse__c = warehouse.Id
        );
        products.add(product2);
        insert products;
    }

    static testMethod void ProductTableController() {
        List<Product_Table__c> allProducts = new List<Product_Table__c>();
        allProducts = [
                SELECT Id, Name, Image_Url__c, Product_Description__c, Unit_Price__c
                FROM Product_Table__c
                ORDER BY Name ASC
                LIMIT 100
        ];

        Test.startTest();
        ProductTableController productTable = new ProductTableController();

        System.debug('Expected=== ' + allProducts);
        System.debug('Actual=== ' + productTable.productsList);

        System.assertEquals(allProducts, productTable.productsList);
        System.assertEquals(allProducts.size(), productTable.productsList.size());
        Test.stopTest();
    }

    static testMethod void buyTest() {
        List<Product_Table__c> allProducts = new List<Product_Table__c>();
        allProducts = [
                SELECT Id, Name, Image_Url__c, Product_Description__c, Unit_Price__c
                FROM Product_Table__c
        ];

        Test.startTest();
        ProductTableController productTable = new ProductTableController();
        productTable.productId = allProducts[0].Id;

        PageReference pageRef = productTable.buy();

        System.debug('Expected=== ' + allProducts[0].Id);
        System.debug('Actual=== ' + pageRef.getParameters().get('Id'));

        System.assertEquals(allProducts[0].Id, pageRef.getParameters().get('Id'));
        Test.stopTest();
    }

    static testMethod void redirectBack_Test() {
        List<Product_Table__c> allProducts = new List<Product_Table__c>();
        allProducts = [
                SELECT Id, Name, Image_Url__c, Product_Description__c, Unit_Price__c
                FROM Product_Table__c
        ];

        Test.startTest();
        ProductTableController productTable = new ProductTableController();
        productTable.productId = allProducts[0].Id;

        PageReference pageReference = Page.OrderTableVF;
        pageReference.getParameters().put('Id', String.valueOf(productTable.productId));
        Test.setCurrentPage(pageReference);
        pageReference = productTable.redirectBack();

        PageReference pageRefProductTableVF = Page.ProductTableVF;

        System.debug('Expected=== ' + pageRefProductTableVF.getUrl());
        System.debug('Actual=== ' + pageReference.getUrl());

        System.assertEquals(pageRefProductTableVF.getUrl(), pageReference.getUrl());
        Test.stopTest();
    }
}